name: Cypress Tests in Docker

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: E2E on Chrome 
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001

    steps:
      # Завантаження коду з репозиторію
      - uses: actions/checkout@v4

      # Встановлення залежностей
      - name: Install dependencies
        run: npm ci

      # Запуск тестів Cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome # запуск тестів в Chrome

      # Завантаження результатів та артефактів у випадку помилки
      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos